### ISSUE TITLE
review general structure of the book

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/OxinferOnboarding#6]
To review the general structure of the book and see if there are things missing (more topic: e.g. Github chapter? OHDSI chapter?, ...)

**Comment by martaalcalde** [comment]
The overall general structure of the book looks great. Here are my comments for improvement:
- Adding a chapter on OHDSI and introducing the OMOP common data model would be beneficial.
- Consider moving  Chapter 2 (Useful people and things to know) to the end (after Chapter 8). This relocation would allow the readers to connect the topics to the relevant people and resources after they have been introduced to all the content.

**Comment by catalamarti** [comment]
done thanks @martaalcalde
